version: 0.2

phases:
  install:
    runtime-versions:
      python: latest

  pre_build:
    commands:
      - echo "Retrieving GitHub PAT from AWS Secrets Manager..."
      - export GITHUB_PAT=$(aws secretsmanager get-secret-value --secret-id github/access_aws --region us-east-2 --query SecretString --output text | sed 's/"//g')
      - echo "Configuring Git to use the PAT..."
      - git config --global user.email "codebuild@example.com"
      - git config --global user.name "AWS CodeBuild"
      - git config --global credential.helper store
      - echo "https://x-access-token:$GITHUB_PAT@github.com" > ~/.git-credentials

  build:
    commands:
      - echo "Cloning the GitHub repository..."
      - git clone https://x-access-token:$GITHUB_PAT@github.com/Nripendra101/github-to-pipeline_nri.git
      - cd github-to-pipeline_nri
      - echo "Zipping the package for Lambda deployment..."
      - zip -r function.zip .

  post_build:
    commands:
      - echo "Deploying Lambda function (nrip-test)..."
      - aws lambda update-function-code --function-name nrip-test --zip-file fileb://function.zip
      - echo "Deployment complete!"
